apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service_port }}
  selector:
    app: {{ .Values.application_name }}
  type: LoadBalancer